### ISSUE TITLE
Toronto SSC is currently using the Toronto LessWrong meetup.com group

### ISSUE THREAD

**Issue by JessRiedel** [ssc-meetups-community/meetups#1]
Toronto SSC has taken over the (previously dormant) Toronto LessWrong meetup.com group:

https://www.meetup.com/Less-Wrong-Toronto/

Our SSC meetup the past Saturday was successful (>25 attendees) and we are having another meeting on May 27th.

https://www.meetup.com/Less-Wrong-Toronto/events/239451798/

**Comment by ssc-fans-hki** [comment]
Thanks for update.
