### ISSUE TITLE
Los Angeles Meetup Details

### ISSUE THREAD

**Issue by b0b3rt** [ssc-meetups-community/meetups#11]
Location: Wine Bar next to the Landmark Theater in the Westside Pavilion (10800 W Pico Blvd #312, Los Angeles, CA 90064).

Time: 7 pm (Every Wednesday)

Parking: Available in the parking lot for the entire complex.  The first three (3) hours are free and do not require validation.  After that, parking is $3 for up to the fifth (5) hour, with validation.

Contact: Google Group (https://groups.google.com/forum/#!forum/lw-socal-announce), personal email (bobert.mushky (at) gmail.com).  Use either to request an invitation to the Google Hangouts group we use for live updates (though meetup/topic announcements are posted every week to the Google Group, which sends out email notifications if you join).

We've had successful meetups every Wednesday since April 5th and plan to continue indefinitely.

**Comment by ssc-fans-hki** [comment]
Thanks for info. Updated Los Angeles in 7fdaceb9dfce150dd28790884cdca0f029bbe3d6
