### ISSUE TITLE
Toronto Meetup August 5th

### ISSUE THREAD

**Issue by JessRiedel** [ssc-meetups-community/meetups#12]
We've scheduled a meetup for Saturday at the Toronto SSC group on August 5th.

https://www.meetup.com/Less-Wrong-Toronto/events/242150520/

Incidentally, I found the main meetups webpage ( ssc-meetups-community.github.io/meetups/ ) very confusing.  It doesn't make sense for a new prospective attendee to have to scroll down through several questions aimed at organizers to finally find the instructions "How to use this repository?...Press Ctrl-F in your web browser".  It should be right at the top, not below the fold!

**Comment by ssc-fans-hki** [comment]
Thanks for the Toronto update and the excellent suggestion. Originally the "how to" instruction was near the top, but since the beginning we have added more and more *other* advice and didn't notice that "Ctrl-F" dropped out of sight. I moved it back.
