### ISSUE TITLE
Updated Portland Meetup Info

### ISSUE THREAD

**Issue by nwalton125** [ssc-meetups-community/meetups#14]
I formatted some updated information for the Portland SSC meetup -- please add this to the repository. Thanks!

* Portland, Oregon
    * [Regular meetups:] We meet the second weekend of each month, alternating Saturdays and Sundays.
    * Meetup scheduled: Saturday, August 12, 2017,  12:30  PM  
    * Location: Contact Noah for the location, or request to join the Facebook group (email and link below) 
    * [Details:] You can RSVP at https://rsvp.glitch.me/
    * [Previous meetups:]
        - Saturday, April 8, 2017,  12:30  PM
        - Sunday, May 7, 2017,  12:30  PM
        - Saturday, June 10, 2017,  12:30  PM
        - Sunday, July 9, 2017,  12:30  PM

    * Contact: nwalton125@gmail.com, [https://www.facebook.com/groups/176053406267595/]

**Comment by clairemingyuan** [comment]
Done, thank you for the information!
