### ISSUE TITLE
SSC Meetup Google Group created for Washington, DC

### ISSUE THREAD

**Issue by robirahman** [ssc-meetups-community/meetups#17]
Here's the link:

https://groups.google.com/forum/#!forum/dc-slatestarcodex

Our next meetup is on August 19th, which is already on the meetup repository page.

**Comment by ssc-fans-hki** [comment]
Thanks for the update, added in b283ec4a7f0b07ae316edc9ff0be1bbd2b55fa71 . Sorry about the delay!
