### ISSUE TITLE
Meetup in Madrid

### ISSUE THREAD

**Issue by pablo-vs** [ssc-meetups-community/meetups#38]
* Madrid
  * Additional search keywords: Spain, España
  * Regular meetups: In planning. We don't have a specific schedule yet, but expect about 2 meetups/month.
  * Meetup scheduled: Wednesday, April 4, 2018,  6:30  PM
  * Location: Complutense University of Madrid, Faculty of Mathematics. Classroom 209
    	      (Ciudad Universitaria, Plaza Ciencias, 3, 28040 Madrid)
  * Details: This is an Effective Altruism / Rationality group, but a lot of members are SSC readers and we will welcome you!
    	       We might create a dedicated SSC group if enough people are interested.
  * Previous meetups:
    - Tuesday, April 20, 2017,  6  PM
  * Contact: Contact details
    - [FB group](https://www.facebook.com/groups/AltruismoEfectivo/)
    - [Meetup.com](https://www.meetup.com/Effective-Altruism-en-Madrid/)
    - eamadrid (at) effectivealtruismhub.com
    - pavill01 (at) ucm.es

**Comment by tripu** [comment]
@pablo-vs, see #39.

(Sorry, I submitted the PR before I saw this issue&hellip; :worried:)

**Comment by pablo-vs** [comment]
Never mind, I was thinking about doing the PR myself!
