### ISSUE TITLE
Update to Wellington

### ISSUE THREAD

**Issue by CalebWithers** [ssc-meetups-community/meetups#4]
* Wellington
    * Additional search keywords: New Zealand
    * Meetup scheduled: Friday, May 19, 2017, 6PM
    * Location: Hashigo Zake
    * Previous meetups:
        - Thursday, April 20, 2017, 6PM
    * Contact: CalebWithersNZ on Facebook, calebwithers[ a t ]gmail.com, 0221371337
        - Consider making contact if you're showing up for the first time, so you can be kept in the loop if there are any last-minute location changes etc.

**Comment by ssc-fans-hki** [comment]
Thanks for the update! (updates to Wellington done in ada1bf4119c15cdc80103c1dab55dfb9b3aec4dd )

edit. fixed link
